### ISSUE TITLE
Test comunicare

### ISSUE THREAD

**Issue by haloandrei** [ABC-practica-2024/BlackPearl#23]
- [x] Testeaza comunicarea intre controller si barca Rpi -> ESP32, depends on #21   , #18 
- [x] Testeaza comunicarea intre controller si frontend pe Rpi, depends on #20
- [x] Testeaza comunicarea intre frontend si telefon Rpi -> Smartphone, depends on #20
